# Use Node.js version 20 LTS as the base image for the frontend
FROM node:20 AS frontend-builder

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json to the working directory
COPY frontend/package.json .

# Install dependencies
RUN npm install npm@latest -g
RUN npm install

# Copy the entire frontend directory
COPY frontend/ .

# Expose the port the app will run on
EXPOSE 5173

# Command to run the frontend in development mode
CMD ["npm", "run", "dev"]