services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
    environment:
      - API_KEY=your_API_key
      - DB_URI=mongodb://mongodb:27017/movietest

volumes:
  mongodb_data:
